(defun main (a) 
    (print a)
    (setq lst6 [1, 2, 3])
    (print lst6)
    (setq lst5 [ "1", "2", "3"])
    (print lst5)
    (print lst)
    (setq lst [q1, q2, q3])
    (print lst)
    (setq lst1 (append lst "q4"))
    (print lst1)
    (print (length lst1))
    (setq lst3 (slice lst1 2 nil))
    (print lst3)
    (print (item lst1 2))
    (setq lst4 (split "а роза упала на лапу азора" " "))
    (print lst4)
    (print (length lst4))
    (setq str1 (join lst4 " "))
    (print str1)
)
 