(defun main (a)
;;        (princ "input ") 
;;        (princ a) 
;;        (princ " type ") 
;;        (princ (type a))
        (print "input " a " type " (type a))
        (setq i (make_iter a))
	(loop (eq i nil)
                (setq k1 (iterate_item i))
		(print k1)
		(if (typep a dict)
		        (progn
                		(setq v1 (item a k1))
				(print v1)
			)
;;			(print "")
		)
        	(setq i (iterate i))
;;        	(print i)
	)
)

(defun init ()
	(print "hello froim init")
)
 