(defun main (a)
    (setq lib_name "../Shared/std_windows/file.dll")
    (setq result1 (load_lib lib_name))
;;    (print result1)
    (setq arg1 ["test.txt", "r"])
;;    (print arg1)
    (setq result2 (call_lib_func lib_name "FileOpen" arg1))
;;    (print result2)
    (setq arr2 (make_array 0))
    (setq arg4 (append arr2 result2))
;;    (print arg4)
    (setq result3 (call_lib_func lib_name "FileSize" arg4))
    (print "file size")
    (print result3)
    (setq arr3 (make_array 0))
    (setq arg5 (append arr3 result2))
    (setq arg5 (append arg5 0))
    (setq arg5 (append arg5 0))
    (setq result4 (call_lib_func lib_name "FilePos" arg5))
    (print "file pos")
    (print result4)
    (setq arr (make_array 0))
    (setq arg3 (append arr result2))
    (setq arg3 (append arg3 10))
;;    (print "arg3")
;;    (print arg3)
    (setq result3 (call_lib_func lib_name "FileRead" arg3))
    (print "read")(print result3)
    (setq arr (make_array 0))
    (setq arg2 (append arr result2))
;;    (print "arg2")
;;    (print arg2)
    (setq result4 (call_lib_func lib_name "FileClose" arg2))
    (print result4)
)
 