(defun main (a)
	(setq l1 (cons "a" (cons "b" nil)))
	(print l1)
;;	(print (car l1))
;;	(print (cdr l1))
	(loop (eq l1 nil)
		(print (car l1))
		(setq l1 (cdr l1))
;;		(print l1)
	) 
;;	(setq i 10)
;;	(loop (eq i 0) 
;;		(print "yes")
;;		(print "no")
;;		(print a)
;;      	(setq i (- i 1))
;;        	(print i)
;;	)
)
 